version: "3"

services:
  eosiodev:
    build:
      context: ./services/eosio
      dockerfile: Dockerfile
    image: dmeetup/eosdev
    stop_grace_period: 3m0s
    command: /opt/eosio/bin/nodeos --config-dir /opt/application/config --data-dir /root/.local/share -e
    ports:
      - "8888:8888"
      - "9830:9876"
    volumes:
      - eosiodevapp:/root/.local/share
      - ./services/eos-dev:/opt/application


volumes:
  eosiodevapp: